# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f957f91f31be1ce651cfafde77c0a7a5254a9079ea5f47d2b8a2a279e81400c01b683fae274857b6a3c6e8a56eb7c4dad431b37d7641a2eeaaaf5328e8813c5

test:
  secret_key_base: ec833eb231b504d87354c42826dc06f350bbb2b2d6740e3d09238e07f2d71009bb01f3529facf984926a6a77f325a03a3f57ae8627bb3a1d1c5705d1e4eb13eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
